# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('semester', models.CharField(blank=True, max_length=2, null=True)),
                ('credits', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='links',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapp.Subjects'),
        ),
    ]
