# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0004_auto_20170725_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='domain',
            field=models.CharField(choices=[('CN', 'Class Notes'), ('QB', 'Question Bank'), ('SN', 'Staff Notes'), ('TQ', 'Test Questions')], default='default', max_length=5),
            preserve_default=False,
        ),
    ]
