# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0005_link_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='domain',
            new_name='notesType',
        ),
    ]
