# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-13 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0006_auto_20171013_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.CharField(default='def', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(default='def', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='credits',
            field=models.CharField(default='def', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(default='def', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
