# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 16:20
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0008_auto_20171014_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='infoType',
        ),
        migrations.AddField(
            model_name='info',
            name='subInfos',
            field=jsonfield.fields.JSONCharField(blank=True, max_length=1000, null=True),
        ),
    ]
