# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-14 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0009_auto_20171014_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='infoSection',
            new_name='infoType',
        ),
        migrations.RenameField(
            model_name='info',
            old_name='text',
            new_name='title',
        ),
    ]
