# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-15 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0010_auto_20171014_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='subInfos',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
