# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-15 16:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0011_auto_20171015_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='date',
            field=models.DateField(default=datetime.date(2017, 10, 15)),
            preserve_default=False,
        ),
    ]
